name: PRIMIS-TECH-V1
services:
  - name: PRIMIS-TECH-V1
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
